### ISSUE TITLE
Use master instead of gh-pages

### ISSUE THREAD

**Issue by klmr** [yegor256/jekyll-github-deploy#19]
Currently, the upstream branch name `gh-pages` is hard-coded. However, when using Github user pages (rather than project pages), Github requires the website to be in the `master` branch, and there doesn’t seem to be a way of changing this configuration.

Would it be possible for jgd to detect whether it needs to push to `gh-pages` or to `master`?

**Comment by yegor256** [comment]
@klmr yes, this is definitely a good idea. Let me try to implement it...

**Comment by yegor256** [comment]
@rultor release, tag is `1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `1.7`

**Comment by yegor256** [comment]
@klmr pls check version 1.7. You can specify branch name:

```
jgd --branch=master
```

**Comment by klmr** [comment]
Awesome, thanks
