### ISSUE TITLE
[broken][ruby 2.2.1] output of `git config --get remote.origin.url` terminates with newline

### ISSUE THREAD

**Issue by torbjoernk** [yegor256/jekyll-github-deploy#21]
The output of `git config --get remote.origin.url` to get the repository URL terminates with a newline, breaking the final system call to the bash script.

Fix: call `String#strip` on the output (c.f. [`/bin/jgd` line 18](https://github.com/yegor256/jekyll-github-deploy/blob/master/bin/jgd#L18))

I've tested that with Ruby 2.2.1.

**Comment by yegor256** [comment]
@torbjoernk pull request was merged, thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `1.7.1`

**Comment by yegor256** [comment]
@torbjoernk try version 1.7.1, it contains your fix

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @torbjoernk please take a look

**Comment by torbjoernk** [comment]
Seems to work fine. Thanks a lot for the fast fix!
