### ISSUE TITLE
Modify deploy.sh to set JEKYLL_ENV=production ?

### ISSUE THREAD

**Issue by clayh53** [yegor256/jekyll-github-deploy#25]
This is one of the cleanest 'deploy to gh-pages' solutions I have run across.

One suggestion that would be very helpful is to modify line 25 in deploy.sh from

```jekyll build --config _config.yml,_config-deploy.yml```

to 

```JEKYLL_ENV=production jekyll build --config _config.yml,_config-deploy.yml```

so that I can conditionally load the analytics code *only* if it is being pushed to the gh-pages branch.

Any thoughts?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by clayh53** [comment]
I'm not sure this is a big issue. I was able to easily fix my immediate problem by adding my Google Analytics tracking code to the ```-config-deploy.yml``` file and then adding a condition in the ```head.html``` include file like this:
```
{% if site.google_analytics %}
  {% include analytics.html %}
{% endif %}
```
And it only loads the analytics code when pushing to gh-pages (e.g. production)

**Comment by clayh53** [comment]
I'm reviving this thread because of a small behavior I noticed. When using jgd to update a gh-pages branch that has a custom domain name, the remote wipe deletes the CNAME file. Is there a way the deploy script can get rid of everything except that file when doing an update?

**Comment by yegor256** [comment]
@clayh53 you can call it like this:

```
JEKYLL_ENV=production jgd
```

Should work, I guess. About the other issue, would be great if you submit a separate ticket.

**Comment by yegor256** [comment]
@clayh53 thanks, I'm closing

**Comment by 0crat** [comment]
Job `gh:yegor256/jekyll-github-deploy#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
