### ISSUE TITLE
CNAME has been removed after deploying

### ISSUE THREAD

**Issue by sasha-travkina** [yegor256/jekyll-github-deploy#29]
Hi! I have custom domain on my site, but I have small problem after using jekyll github deploy. My CNAME file has been removed from gh-pages branch after deploying. How I can decide this trouble?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@sasha-travkina put that file into master branch and it will copied to `gh-pages` during deploy. See how it works in my blog: https://github.com/yegor256/blog

**Comment by sasha-travkina** [comment]
@yegor256 I have a CNAME file in my master branch, but after deploy he still be removed from gh-pages.

**Comment by sasha-travkina** [comment]
Well, it's my fault. CNAME was be excluded on blog in configuration file. Thanks for you help!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jekyll-github-deploy#29` was not in scope
